image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

  steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Install Docker manually
    run: |
      set -e

      sudo mkdir -p /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

      sudo apt-get update
      sudo apt-get remove -y moby-engine moby-cli || echo "No moby to remove"

      sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      docker --version
      sudo systemctl status docker --no-pager

  - name: Build Docker Image
    run: docker build -f Dockerfile -t myapp:latest .

  - name: Docker Scout Scan
    uses: docker/scout-action@v1.0.9
    with:
      dockerhub-user: ${{ secrets.REPO_USER }}
      dockerhub-password: ${{ secrets.REPO_PWD }}
      command: quickview,cves
      only-severities: critical,high
      sarif-file: scout-report.sarif

  - name: Upload Artifact
    uses: actions/upload-artifact@v4
    if: always()
    with:
      name: docker-scout-findings
      path: scout-report.sarif
